### ISSUE TITLE
`tree-view-mode` hardcoded to work only with `evil-tree-edit`

### ISSUE THREAD

**Issue by Honeypot95** [ethan-leba/tree-edit#50]
Hi! I recently tried to run the code, and got prompted by this message:
```tree-edit-view--setup: Sorry, I hardcoded this mode to only work with evil-tree-edit. Please remind me if I forgot!```

I understand that this is a work in progress and I do not expect this to be fixed soon (or at all, as you owe nothing to us), but I wanted to ask if the code may be ready for use without `evil-tree-edit` and you just forgot about the prompt!

In any case, I thought that it may be useful to keep this github issue open until that changes.

Thank you!

**Comment by ethan-leba** [comment]
Ah, yeah I should probably fix that! `tree-edit-view-mode` is a 'fork' of `tree-sitter-debug-mode`, so you could use that in it's place. That said, the library of tree-edit _should_ be completely useable without evil (examples [here](https://github.com/ethan-leba/tree-edit/blob/main/doc/using-tree-edit.org)). If you're looking for a prepackaged non-evil mode with keybindings, that unfortunately doesn't exist yet, but @fgeller has a work-in-progress that we're discussing in #40.

Did you trigger `M-x tree-edit-view-mode` manually, or was that a side effect of some other command? Just curious how you ran up against that error.

Thanks for checking out my project!

**Comment by ethan-leba** [comment]
e5aab26 * refactor: move tree-view to evil package
