### ISSUE TITLE
Cannot insert new child node in empty module

### ISSUE THREAD

**Issue by nobellium1997** [ethan-leba/tree-edit#55]
When creating a new, empty module in python, adding child nodes to the root of the tree doesn't seem to work. It seems like tree-edit is expecting place holder nodes to make sense of what is going on but with a completely new file, inserting child nodes doesn't seem to work.

Using emacs 28 using tree-edit on commit 6d8e495169d4e6bb98b3cd1a1a0a06cc806c5e59

### Repro steps:
- Create or open a blank or empty file
- Enable tree-edit mode
- Insert a new child class in the module

Expected: new child class node
Actual: Error message "let: Wrong type argument: user-ptrp, nil"

**Comment by ethan-leba** [comment]
Thanks for the report!

Insert child is written prettily jankily, one of the assumptions is that the node already has children which is not true for an empty module. I can just special case the root node for this since I assume that's the only node that could have no children.

**Comment by ethan-leba** [comment]
Fixed by b6249da
