### ISSUE TITLE
Java error: Symbol’s value as variable is void: q When trying to insert anything in java mode

### ISSUE THREAD

**Issue by Ice-Cube69** [ethan-leba/tree-edit#60]
Whenever I try to insert something in java, I get the error ```tree-edit--valid-insertions: Symbol’s value as variable is void: q```.
Here is my config: 
```lisp
  (use-package tree-edit)
  (use-package evil-tree-edit)
```
However it works for python.

**Comment by Ice-Cube69** [comment]
I am using emacs 28.0, as for the stack trace, I'm not exactly sure how to do that. 
Steps to reproduce: 
1. Select a method node.
2. Press im for insert method

**Comment by ethan-leba** [comment]
I was able to reproduce after testing when the code was native-compiled, should be fixed by 774a1e9. Let me know if it works for you now!

**Comment by Ice-Cube69** [comment]
Yeah, now it works great!
